-- mapowanie klawiszy keys.lua
vim.g.mapleader = " "

vim.keymap.set('n', '<c-n>', '<cmd>lua require"gitsigns.actions".next_hunk()<CR>zv')
vim.keymap.set('n', '<c-p>', '<cmd>lua require"gitsigns.actions".prev_hunk()<CR>zv')
vim.keymap.set('n', '<leader>,', '<cmd>bp<cr>')
vim.keymap.set('n', '<leader>.', '<cmd>bn<cr>')
vim.keymap.set('n', '<leader>;', ':')
vim.keymap.set('n', '<leader>B', '<cmd>Telescope buffers<cr>')
vim.keymap.set('n', '<leader>b', '<cmd>BufferPick<cr>')
vim.keymap.set('n', '<leader>c', '<cmd>close<cr>')
vim.keymap.set('n', '<leader>d', '<cmd>bd<cr>')
vim.keymap.set('n', '<leader>f', '<cmd>Telescope find_files<cr>')
vim.keymap.set('n', '<leader>g', '<cmd>Telescope live_grep<cr>')
vim.keymap.set('n', '<leader>n', '<cmd>NvimTreeToggle<cr>')
vim.keymap.set('n', '<leader>o', '<cmd>only<cr>')
vim.keymap.set('n', '<leader>q', '<cmd>q<cr>')
vim.keymap.set('n', '<leader>r', '<cmd>Telescope registers<cr>')
vim.keymap.set('n', '<leader>so', '<cmd>luafile %<cr><cmd>echo "Plik przeładowany ..."<cr>')
vim.keymap.set('n', '<leader>sp', '<cmd>sp<cr>')
vim.keymap.set('n', '<leader>u', '<cmd>UndotreeToggle<cr>')
vim.keymap.set('n', '<leader>vs', '<cmd>vs<cr>')
vim.keymap.set('n', '<leader>w', '<cmd>w<cr>')
vim.keymap.set('n', '<tab>', '<cmd>e #<cr>')
vim.keymap.set('n', 'dh', 'xd0')
vim.keymap.set('n', 'dl', 'd$')
vim.keymap.set('n', 'gf', '<cmd>edit <cfile><cr>')
vim.keymap.set('n', 'gh', '0')
vim.keymap.set('n', 'gj', '<cmd>lua require"gitsigns.actions".next_hunk()<CR>zv')
vim.keymap.set('n', 'gk', '<cmd>lua require"gitsigns.actions".prev_hunk()<CR>zv')
vim.keymap.set('n', 'gl', '$')
vim.keymap.set('n', 'qq', '<cmd>q<cr>')
vim.keymap.set('n', 'zm', 'zn')
vim.keymap.set('n', 'zn', 'zm')
vim.keymap.set('x', 'gh', '0')
vim.keymap.set('x', 'gl', '$')
